---
- name: Disable Logstash service at startup
  systemd:
    name: logstash
    enabled: no

- name: "Set Logstash minimum heap size"
  lineinfile:
    dest: /etc/logstash/jvm.options
    regexp: '^-Xms'
    line: "-Xms{{ logstash_java_heap_size }}"
  notify:
    - Restart Logstash

- name: "Set Logstash maximum heap size"
  lineinfile:
    dest: /etc/logstash/jvm.options
    regexp: '^-Xmx'
    line: "-Xmx{{ logstash_java_heap_size }}"
  notify:
    - Restart Logstash

- name: Compute Logstash debug mode
  set_fact:
    logstash_debug: "{{ 'true' if logstash_debug_mode else 'false' }}"
    logstash_log_level: "{{ 'debug' if logstash_debug_mode else 'info' }}"

- name: "Set Logstash log level"
  lineinfile:
    dest: /etc/logstash/logstash.yml
    regexp: '^log\.level:'
    line: "log.level: {{ logstash_log_level }}"
  notify:
    - Restart Logstash

- name: "Set Logstash debug mode"
  lineinfile:
    dest: /etc/logstash/logstash.yml
    regexp: '^config\.debug:'
    line: "config.debug: {{ logstash_debug }}"
  notify:
    - Restart Logstash

- name: "Add current user to Logstash group"
  user:
    name: "{{ lookup('env','USER') }}"
    groups: "logstash"
    append: yes
