version: '3'

services:

  titan-project-backend:
    restart: always
    build: ./backend
    ports:
      - "8081:8081"

  titan-project-frontend:
    restart: always
    build: 
      context: ./frontend
      args:
        BACKENDHOST: "localhost:8081"
    ports:
     - "8080:80"

