version: '3'

services:

  titan-project-frontend:
    restart: always
    build: 
      context: ./frontend
      args:
        BACKENDHOST: "localhost:8081"
    ports:
     - "8080:80"

  titan-project-backend:
    restart: always
    build: 
      context: ./backend
    environment:
      - LOGSTASH_ROOT_DIR=/tmp/logstash/
    ports:
      - "8081:8081"
    user: root
    volumes:
      - /tmp/logstash/:/tmp/logstash/
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  titan-project-logfiles:
