version: '3'

services:

  titan-project-frontend:
    restart: always
    build: 
      context: ./frontend
      args:
        BACKENDHOST: "localhost:8081"
        #  http_proxy: ""
        #  https_proxy: ""
        #  no_proxy: ""
    ports:
     - "8080:80"

  titan-project-backend:
    restart: always
    build: 
      context: ./backend
     # args:
      #  http_proxy: ""
      #  https_proxy: ""
      #  no_proxy: ""
    environment:
      - LOGSTASH_ROOT_DIR=/tmp/logstash/
    ports:
      - "8081:8081"
    volumes:
      - /tmp/logstash/:/tmp/logstash/
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  titan-project-logfiles:
