version: '3'

services:

  titan-project-frontend:
    restart: always
    build: 
      context: ./frontend
      args:
        BACKENDHOST: "localhost:8081"
        #  http_proxy: ""
        #  https_proxy: ""
        #  no_proxy: ""
    ports:
     - "8080:80"

  titan-project-backend:
    restart: always
    build: 
      context: ./backend
     # args:
      #  http_proxy: ""
      #  https_proxy: ""
      #  no_proxy: ""
    environment:
        - LOGFILES_DIR=/data/logfiles/
    ports:
      - "8081:8081"
    volumes:
      - titan-project-logfiles:/data/logfiles/
    networks:
      - titan_project_backend_network

volumes:
  titan-project-logfiles:

networks:
  titan_project_backend_network:
