version: '3'

services:

  titan-project-backend:
    restart: always
    build: 
      context: ./backend
     # args:
      #  http_proxy: ""
      #  https_proxy: ""
      #  no_proxy: ""
    environment:
        - LOGFILES_DIR=/data/logfiles/
    ports:
      - "8081:8081"
    volumes:
      - titan-project-logfiles:/data/logfiles/

volumes:
  titan-project-logfiles: