version: '3'

services:

  titan-project-backend:
    restart: always
    build: 
      context: .
    environment:
      - LOGSTASH_ROOT_DIR=/tmp/logstash/
    ports:
      - "8081:8081"
    user: root
    volumes:
      - /tmp/logstash/:/tmp/logstash/
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  titan-project-logfiles:
