version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    restart: unless-stopped
    environment:
      - NETWORK_HOST="0.0.0.0"
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk_network

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    restart: unless-stopped
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      SERVER_HOST: "0.0.0.0"
    ports:
      - 5601:5601
    networks:
      - elk_network

volumes:
  es_data:
    driver: local

networks:
  elk_network:
