---
- name: Install python
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-pip

- name: Install python dependencies
  become: false
  pip:
    name: "{{ item }}"
    executable: pip2
  with_items:
    - "{{ python_pip_modules }}"