---
- name: System upgrade
  apt:
    update_cache: yes
    upgrade: dist
    force: yes
  listen: "Update Logstash"

- name: Restart Logstash
  systemd:
    name: logstash
    state: restarted
  listen: "Update Logstash"
